Repository enwikipedia-acc/waca, pull requests merged in 2022-08, with the labels that each got.

#749 Docker improvements
  Dockerfile
  docker-compose.yml
  docker/rabbitmq.conf
Labels: trivial

#733 Assign users to domains
  includes/DataObjects/Domain.php
  includes/Pages/PageDomainManagement.php
  includes/Pages/Registration/PageRegisterBase.php
  includes/Pages/Registration/PageRegisterOption.php
  includes/Pages/UserAuth/Login/LoginCredentialPageBase.php
  includes/Pages/UserAuth/PageOAuthCallback.php
  includes/Security/DomainAccessManager.php
  includes/SiteConfiguration.php
  sql/patches/patch40-userdomains.sql
  templates/domain-management/edit.tpl
  templates/domain-management/main.tpl
  templates/navigation-menu.tpl
  templates/registration/option.tpl
  templates/registration/register.tpl
Labels: schema changes

#754 Fix queue creation
  includes/Pages/PageQueueManagement.php
Labels: trivial

#755 Fix SearchHelper IN() clause construction
  includes/ConsoleTasks/ClearOAuthDataTask.php
  includes/Helpers/SearchHelpers/SearchHelperBase.php
Labels: performance

#741 Use Reply-To instead of From
  config.inc.php
  includes/ApplicationBase.php
  includes/DataObjects/Domain.php
  includes/Helpers/EmailHelper.php
  includes/Helpers/Interfaces/IEmailHelper.php
  includes/Helpers/RequestEmailHelper.php
  includes/Pages/PageDomainManagement.php
  includes/Pages/PageUserManagement.php
  includes/Pages/Request/PageRequestAccount.php
  includes/Pages/UserAuth/PageForgotPassword.php
  includes/SiteConfiguration.php
  sql/patches/patch41-requestform-usage.sql
  sql/patches/patch42-renamefield.sql
  templates/domain-management/edit.tpl
  templates/domain-management/main.tpl
Labels: Priority: High
